<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>k</string>
	</array>
	<key>foldingEndMarker</key>
	<string>^\s*\}</string>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>name</key>
	<string>Kronos</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.language.kronos</string>
		</dict>
		<dict>
				<key>match</key>
				<string>#\[[^\]]*\]</string>
				<key>name</key>
				<string>entity.other.attribute-name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(Import|Use|Package)</string>
			<key>name</key>
			<string>keyword.packages.kronos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([a-zA-Z:][a-zA-Z0-9!?\-+:/~%#\*`]*\(|\{|\}|\(|\))</string>
			<key>name</key>
			<string>support.function.kronos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z:][a-zA-Z0-9!?\-+:]*</string>
			<key>name</key>
			<string>entity.name.kronos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#-?[0-9]*\.?[0-9]+</string>
			<key>name</key>
			<string>constant.language.kronos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"(\\.|[^\\])*?"</string>
			<key>name</key>
			<string>string.kronos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]*\.?[0-9]+([dqi]|)</string>
			<key>name</key>
			<string>constant.numeric.kronos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([:+\-/*&amp;|]|==|&gt;=|=&gt;|&lt;=|&lt;&lt;|&gt;&gt;|=)</string>
			<key>name</key>
			<string>keyword.operator.kronos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(Import|Use|Package|Type)\s</string>
			<key>name</key>
			<string>keyword.control.import.kronos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(When|Let)\s</string>
			<key>name</key>
			<string>keyword.control.kronos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\{\}]</string>
			<key>name</key>
			<string>keyword.scope.kronos</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kronos</string>
	<key>uuid</key>
	<string>e621f7b0-d1cc-4fd5-87a2-e82fb4fed3e3</string>
</dict>
</plist>
