#pragma once

static const char* animal_name[] = {
"aardvark",
"albatross",
"alligator",
"alpaca",
"ant",
"anteater",
"antelope",
"ape",
"armadillo",
"ass",
"auk",
"baboon",
"badger",
"barracuda",
"bass",
"bat",
"bear",
"beaver",
"bee",
"beetle",
"bird",
"bison",
"bittern",
"bloodhound",
"boar",
"bobcat",
"bovine",
"buffalo",
"bullfinch",
"bullock",
"butterfly",
"buzzard",
"camel",
"caribou",
"cat",
"caterpillar",
"cattle",
"cheetah",
"chicken",
"chimpanzee",
"chinchilla",
"cicada",
"clam",
"cockroach",
"cod",
"colt",
"coot",
"cougar",
"cow",
"coyote",
"crab",
"crane",
"cricket",
"crocodile",
"crow",
"deer",
"dog",
"dolphin",
"donkey",
"dotterel",
"dove",
"duck",
"eagle",
"eel",
"elephant",
"elk",
"ewe",
"falcon",
"ferret",
"finch",
"fish",
"flamingo",
"fly",
"fowl",
"fox",
"frog",
"gerbil",
"giraffe",
"gnat",
"gnu",
"goat",
"goldfinch",
"goldfish",
"goose",
"gorilla",
"goshawk",
"grasshopper",
"greyhound",
"grouse",
"guinea",
"gull",
"hamster",
"hare",
"hawk",
"hedgehog",
"hen",
"heron",
"herring",
"hippopotamus",
"hog",
"hornet",
"horse",
"hound",
"hummingbird",
"hyena",
"hyrax",
"impala",
"jackrabbit",
"jellyfish",
"kangaroo",
"kitten",
"koala",
"lark",
"lemur",
"leopard",
"lice",
"lion",
"llama",
"lobster",
"locust",
"louse",
"lynx",
"mackerel",
"magpie",
"mallard",
"manatee",
"marten",
"meerkat",
"mink",
"minnow",
"mole",
"monkey",
"moose",
"mosquito",
"mouse",
"mule",
"muskrat",
"nighthawk",
"nightingale",
"opossum",
"orangutan",
"ostrich",
"otter",
"owl",
"ox",
"oyster",
"panda",
"parrot",
"partridge",
"peacock",
"peafowl",
"pelican",
"penguin",
"pheasant",
"pig",
"pigeon",
"pike",
"plover",
"polar", 
"polecat",
"pony",
"porcupine",
"porpoise",
"possum",
"prairie", 
"quail",
"rabbit",
"raccoon",
"racoon",
"raptor",
"rat",
"raven",
"reindeer",
"rhinoceros",
"rook",
"rooster",
"salmon",
"sandpiper",
"sardine",
"scorpion",
"seahorse",
"sealion",
"seal",
"shark",
"sheep",
"skunk",
"snail",
"snake",
"snipe",
"sow",
"sparrow",
"spider",
"squirrel",
"stallion",
"starling",
"stork",
"swallow",
"swan",
"swine",
"swordfish",
"termite",
"tiger",
"toad",
"tortoise",
"toucan",
"trout",
"turkey",
"turtle",
"turtledove"
"viper",
"vulture",
"wallaby",
"walrus",
"wasp",
"weasel",
"whale",
"widgeon",
"wolf",
"wombat",
"woodchuck",
"woodcock",
"woodpecker",
"worm",
"wren",
"yak",
"zebra",
};

static const char *adjective[] = {
"admirable", "adorable", "affectionate", "aggressive", "agitated", "angry", "annoyed", "anxious", "appreciated", "arrogant", "ashamed", "authoritative", "averse", "awesome", "awful",
"belligerent", "bitter", "blue", "blunt", "bold", "bored", "brilliant", 
"callous", "cautious", "cheerful", "clever", "combative", "comical", "compassionate", "contemptuous", "content", "contrary", "cool", "cordial", "covetous", "cranky", "cross", "cruel", "curious",
"dainty", "defeated", "defiant", "dejected", "delighted", "despair", "devoted", "disagreeable", "disciplined", "discontent", "disgust", "distaste", "doubtful", "dutiful", "dynamic",
"elated", "enraged", "envious", "evil", "excited", "exhausted",
"fearful", "fearless", "feisty", "fierce", "flattered", "folksy", "forgiving", "forlorn", "frustrated", "furious",
"gay", "generous", "gentle", "gleeful", "grateful", "greedy",
"happy", "harsh", "haughty", "heroic", "honest", "honored", "hostile",
"ignored", "imaginative", "impartial", "impatient", "inconsiderate", "indifferent", "innocent", "inquisitive", "insightful", "inspired", "intuitive", "irate", "isolated",
"jealous",
"kind",
"lazy", "lively", "loathing", "lonely", "lucky",
"mad", "mean", "meek", "melancholy", "mollified",
"nasty", "natural", "naughty", "nervous",
"obnoxious", "obstinate", "outraged", "outstanding", "overjoyed",
"patient", "perky", "powerful", "proud",
"querulous",
"raging", "rapturous", "relaxed", "reliable", "relieved", "reluctant", "repentant", "repulsive", "resigned", "resistant", "restrained", "reverent", "ridiculed", "rough", "rude",
"sad", "satisfied", "scornful", "sick", "silly", "skillful", "spiteful", "stubborn", "sweet",
"tame", "tempted", "tender", "tense", "terse", "tired",
"uncertain", "unhappy",
"valiant", "victorious", "vindictive", "violent", "vocal", "vociferous",
"wary", "weary", "weird", "wicked", "wise", "woeful", "wonderful", "worthy",
"youthful",
"zealous"
};