image: ubuntu/latest
packages:
- libsndfile-dev
- libjack-jackd2-dev
- libz-dev
- cmake
- llvm-6.0-dev
- libcurl4-openssl-dev
- libfmt-dev
secrets:
  - 571eec1e-e160-4e54-a8cf-c44b0b91e1a1
  - 2c57e405-7f00-4c43-b59a-3cc1304e545a
sources:
- hg+https://hg.sr.ht/~vnorilo/kronos
tasks:
- identity: |
    set +x
    cd kronos
    hg sum
- configure: |
    set +x
    mkdir build
    cd build
    cmake ../kronos -DCMAKE_BUILD_TYPE=Release
- authorize-ci: |
    cd kronos
    ~/authorize_ci.sh
- build: |
    cd build
    make -j
- test: |
    cd build
    env CTEST_OUTPUT_ON_FAILURE=1 make test
triggers:
- action: email
  condition: failure
  to: <vn@imap.cc>